apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2023-02-12T20:12:53Z","labels":{"run":"nginx-one"},"name":"nginx-one","namespace":"default","resourceVersion":"6749","uid":"09833ca2-13b5-4bf9-884a-a5c59c5648eb"},"spec":{"clusterIP":"10.96.36.169","clusterIPs":["10.96.36.169"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":31113,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"run":"nginx-one"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2023-02-12T20:12:53Z"
  labels:
    run: nginx-one
  name: nginx-one
  namespace: default
  resourceVersion: "45344"
  uid: 09833ca2-13b5-4bf9-884a-a5c59c5648eb
spec:
  clusterIP: 10.96.36.169
  clusterIPs:
  - 10.96.36.169
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31111
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-one
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
